### ISSUE TITLE
Question: Firework Explosion Damage?

### ISSUE THREAD

**Issue by rxay579** [Blumbo/Boom-Control#2]
I've been browsing through the source code and haven't seen specific mention of it, but can this mod modify the damage done by firework rockets, either launched by hand or by crossbow?

Haven't been able to find a current mod that could control firework damage on 1.19.4 / 1.20.x.

*edit*
Did a quick single player world test and did not see an option for fireworks or generic explosions.
Please consider adding firework explosion control to the list if it is plausible.

Nice options that it does have though.

**Comment by Blumbo** [comment]
That's actually a good idea.
Firework explosions work a bit differently from other explosions tho, and depending on how lazy I am I might or might not add it. Will see if it's there in about a week (probably less if I actually decide to do it)

**Comment by Blumbo** [comment]
Made a separate mod
https://github.com/Blumbo/FireworkControl/releases/tag/1.0.0-1.20.1
